# Базовый образ MYSQL
FROM mysql:latest

# Устанавливаем зависимости системы (если нужны)
# RUN apt update && \
#     apt install -y vim curl wget

ENV MYSQL_DATABASE=emerald_db
ENV MYSQL_USER=emerald
ENV MYSQL_PASSWORD=stong_emerald_p@ssword
ENV MYSQL_ROOT_PASSWORD=JPEqPA05!

EXPOSE 3306